[tox]
env_list = lint-core, lint-examples, unit, packet-visuals, integration
skip_missing_interpreters = true

[testenv]
sitepackages = true
package = skip
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements-test.txt
commands = python -m pytest {posargs}

[testenv:unit]
commands = python -m pytest -m "not integration and not packet_visual" {posargs}

[testenv:packet-visuals]
commands = python -m pytest -m packet_visual {posargs}

[testenv:integration]
commands = python -m pytest -m integration {posargs}

[testenv:lint-core]
deps =
    -r{toxinidir}/requirements-lint.txt
commands =
    python -m flake8 pysap tests extra setup.py docs/conf.py --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    python -m flake8 pysap tests extra setup.py docs/conf.py --count --ignore=E501 --exit-zero --max-complexity=10 --max-line-length=127 --statistics

[testenv:lint-examples]
deps =
    -r{toxinidir}/requirements-lint.txt
commands =
    python -m flake8 examples --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    python -m flake8 examples --count --ignore=E501 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
