[tox]
env_list = lint, unit, integration
skip_missing_interpreters = true

[testenv]
sitepackages = true
package = skip
deps =
    -r{toxinidir}/requirements-test.txt
commands = python -m pytest {posargs}

[testenv:unit]
commands = python -m pytest -m "not integration" {posargs}

[testenv:integration]
commands = python -m pytest -m integration {posargs}

[testenv:lint]
deps =
    -r{toxinidir}/requirements-lint.txt
commands =
    python -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    python -m flake8 . --count --ignore=E501 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
