[tox]
env_list = unit, integration
skip_missing_interpreters = true

[testenv]
sitepackages = true
package = skip
deps =
    -r{toxinidir}/requirements-test.txt
commands = python -m pytest {posargs}

[testenv:unit]
commands = python -m pytest -m "not integration" {posargs}

[testenv:integration]
commands = python -m pytest -m integration {posargs}
